import { Injectable, OnModuleInit, Logger } from '@nestjs/common';
import { SchedulerRegistry } from '@nestjs/schedule';
import { CronJob } from 'cron';
import { PrismaService } from '../prisma/prisma.service';
import { RequerimientosService } from './requerimientos.service';

export interface EmailScheduleConfig {
  enabled: boolean;
  diasSemana: number[];   // 0=Dom 1=Lun ... 6=Sáb
  hora: number;
  minuto: number;
  estados: string[];
  destinatarios: string[];
  asunto?: string;
  mensaje?: string;
  area?: string;
  prioridad?: string;
  /** Si true, filtra solo los tickets que tuvieron una gestión durante la semana en curso */
  filtrarSemanaActual?: boolean;
}

const CONFIG_KEY = 'email_auto_schedule';
const JOB_PREFIX = 'email_schedule_';

@Injectable()
export class EmailSchedulerService implements OnModuleInit {
  private readonly logger = new Logger(EmailSchedulerService.name);

  constructor(
    private prisma: PrismaService,
    private schedulerRegistry: SchedulerRegistry,
    private requerimientosService: RequerimientosService,
  ) {}

  async onModuleInit() {
    const configs = await this.prisma.$queryRaw<{ companyId: string; configValue: string | null }[]>`
      SELECT companyId, configValue FROM ConfiguracionSistema WHERE configKey = ${CONFIG_KEY}
    `;
    for (const row of configs) {
      if (row.configValue) {
        try {
          const cfg: EmailScheduleConfig = JSON.parse(row.configValue);
          if (cfg.enabled) this.registerCron(row.companyId, cfg);
        } catch { /* config inválida */ }
      }
    }
  }

  async getSchedule(companyId: string): Promise<EmailScheduleConfig | null> {
    const rows = await this.prisma.$queryRaw<{ configValue: string | null }[]>`
      SELECT TOP 1 configValue FROM ConfiguracionSistema
      WHERE companyId = ${companyId} AND configKey = ${CONFIG_KEY}
    `;
    if (!rows[0]?.configValue) return null;
    try { return JSON.parse(rows[0].configValue); } catch { return null; }
  }

  async saveSchedule(companyId: string, cfg: EmailScheduleConfig): Promise<void> {
    const configValue = JSON.stringify(cfg);
    const description = 'Automatización de envío de correos de requerimientos';
    // Use raw SQL: SQL Server 2016 MERGE (generated by Prisma upsert) has known bugs
    await this.prisma.$executeRaw`
      IF EXISTS (
        SELECT 1 FROM ConfiguracionSistema
        WHERE companyId = ${companyId} AND configKey = ${CONFIG_KEY}
      )
        UPDATE ConfiguracionSistema
        SET configValue = ${configValue}, updatedAt = GETDATE()
        WHERE companyId = ${companyId} AND configKey = ${CONFIG_KEY}
      ELSE
        INSERT INTO ConfiguracionSistema (id, companyId, configKey, configValue, description, updatedAt)
        VALUES (NEWID(), ${companyId}, ${CONFIG_KEY}, ${configValue}, ${description}, GETDATE())
    `;

    this.removeCron(companyId);
    if (cfg.enabled && cfg.diasSemana.length > 0 && cfg.destinatarios.length > 0) {
      this.registerCron(companyId, cfg);
    }
  }

  async runNow(
    companyId: string,
    override?: Partial<EmailScheduleConfig>,
  ): Promise<{ enviados: number; destinatarios: number }> {
    const saved = await this.getSchedule(companyId);
    // Merge saved config with any override from the request body
    const cfg: EmailScheduleConfig = {
      ...(saved ?? { enabled: true, diasSemana: [], hora: 0, minuto: 0, estados: [], destinatarios: [] }),
      ...override,
    };
    if (!cfg.destinatarios?.length) {
      throw new Error('No hay destinatarios configurados. Agrega al menos un correo.');
    }
    return this.executeScheduledSend(companyId, cfg);
  }

  // ── privados ────────────────────────────────────────────────────────────────

  private registerCron(companyId: string, cfg: EmailScheduleConfig) {
    const cronExpr = this.buildCronExpression(cfg);
    const tz       = Intl.DateTimeFormat().resolvedOptions().timeZone;
    this.logger.log(`Registrando cron [${JOB_PREFIX}${companyId}]: ${cronExpr} timezone=${tz}`);
    const job = new CronJob(cronExpr, () => {
      this.executeScheduledSend(companyId, cfg).catch(err =>
        this.logger.error(`Error en envío automático company=${companyId}: ${err?.message}`),
      );
    }, null, false, tz);
    this.schedulerRegistry.addCronJob(`${JOB_PREFIX}${companyId}`, job);
    job.start();
  }

  private removeCron(companyId: string) {
    const name = `${JOB_PREFIX}${companyId}`;
    try {
      this.schedulerRegistry.deleteCronJob(name);
      this.logger.log(`CronJob ${name} eliminado`);
    } catch { /* no existía */ }
  }

  private buildCronExpression(cfg: EmailScheduleConfig): string {
    const dias = cfg.diasSemana.join(',');
    return `0 ${cfg.minuto} ${cfg.hora} * * ${dias}`;
  }

  private async executeScheduledSend(
    companyId: string,
    cfg: EmailScheduleConfig,
  ): Promise<{ enviados: number; destinatarios: number }> {
    this.logger.log(`Ejecutando envío automático company=${companyId}`);

    // Calcular rango lun–dom de la semana en curso si el filtro está activo
    let gestionDesde: string | undefined;
    let gestionHasta: string | undefined;
    if (cfg.filtrarSemanaActual) {
      const now  = new Date();
      const day  = now.getDay() === 0 ? 6 : now.getDay() - 1; // lun=0 ... dom=6
      const lun  = new Date(now); lun.setDate(now.getDate() - day); lun.setHours(0,0,0,0);
      const dom  = new Date(lun); dom.setDate(lun.getDate() + 6);
      const iso  = (d: Date) => d.toISOString().split('T')[0];
      gestionDesde = iso(lun);
      gestionHasta = iso(dom);
      this.logger.log(`Filtro semana activo: ${gestionDesde} → ${gestionHasta}`);
    }

    return this.requerimientosService.enviarCorreo(companyId, {
      destinatarios:  cfg.destinatarios,
      asunto:         cfg.asunto,
      mensaje:        cfg.mensaje,
      area:           cfg.area || undefined,
      prioridad:      cfg.prioridad || undefined,
      estadosActual:  cfg.estados.length > 0 ? cfg.estados : undefined,
      gestionDesde,
      gestionHasta,
    });
  }
}
