module.exports = {
  apps: [
    {
      name: 'aura-backend',
      script: 'dist/main.js',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_production: {
        NODE_ENV: 'production',
        PORT: 3001,
        ENV_FILE: '.env',
      },
      error_file: 'logs/err.log',
      out_file: 'logs/out.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
    {
      name: 'aura-backend-staging',
      script: 'dist/main.js',
      cwd: './',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '1G',
      env_staging: {
        NODE_ENV: 'staging',
        PORT: 3002,
        ENV_FILE: '.env.staging',
      },
      error_file: 'logs/err-staging.log',
      out_file: 'logs/out-staging.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss',
      merge_logs: true,
    },
  ],
};
